### ISSUE TITLE
Issues with Facebook login

### ISSUE THREAD

**Issue by chrisdivyak** [intoeetive/social_login_pro#1]
I updated my version to 1.8.9 running on EE 2.6. When the Oauth comes back into EE I get the 
```
There has been some problem when communicating to Facebook. Please try again
``` 
error. I have checked all of my Facebook settings and everything looks ok. I assume there was an API update between the last update you made and now. Please advise.

**Comment by JonnyBR12** [comment]
Getting same here. Did you get this resolved?

**Comment by chrisdivyak** [comment]
I was able to fix the problem because we were running a firewall on our side. We added proxy settings into the OAuth files and it fixed the issue. I forked the repo and added the settings. You can find the files on my fork [https://github.com/chrisdivyak/social_login_pro](https://github.com/chrisdivyak/social_login_pro). I hope it works for you as well. I know many other people have had similar issues.
